command:
  Continue: 5
  Default: 0
  Land: 2
  Start: 3
  Stop: 4
  Takeoff: 1
location:
  Lab: 0
  Business Street: 1
  North Teaching Building B: 2
  Luckin Coffee: 3
  Library: 4
  Bell Tower: 5
  Hainaju: 6
  Qizhen Lake: 7
  Dining Hall: 8